Remove obsolete Jemalloc
johnthagen/min-sized-rust pull request #70
Opened 2024-09-07 14:18 UTC by kornelski

Rust 1.31 is [long dead](https://lib.rs/stats#rustc-usage).

2024-09-10 18:43 UTC, 8573 commented
Why delete it entirely, rather than move it to the end, where it will be out of the way of people going down the list for practical use but will still be visible to people who might be interested in what was relevant historically?

2024-09-10 18:47 UTC, johnthagen commented
I too have some reservations about deleting it entirely.

I could accept the PR if it was changed to moving it to a new section at the very bottom titled

```md
# Legacy Techniques

## Remove Jemalloc
...
```

2024-09-10 18:47 UTC, johnthagen requested changes
Please move to a new section at the bottom of the markdown page.

2024-09-10 21:30 UTC, kornelski commented
I've thought about it, but couldn't find any reason to keep it, other than loss aversion.

This default is not in Rust any more. Literally nobody uses Rust so old to benefit from this information. It's just an irrelevant distraction, and it became wrong information diluting usefulness of the guide for everyone. It has negative value.

2024-09-11 07:15 UTC, 8573 commented
> Literally nobody uses Rust so old to benefit from this information.

Not many people now use BSD versions from 30 years ago either, but FreeBSD's source code contains [various historical files](https://svnweb.freebsd.org/csrg/admin/admin/) in case they might be interesting to someone.

> It's just an irrelevant distraction, ... It has negative value.

It may be irrelevant and valueless to you, or to people practically shrinking modern Rust executables, but do you have arguments (rather than mere assertions) as to why keeping some record of this historical technique would be so bad? You say

> it became wrong information diluting usefulness of the guide for everyone

but, if having it at the end is still too much a "distraction", it could be moved to a separate file, linked from the end of the main file.

2024-09-11 11:03 UTC, closed without merging

2024-09-11 11:03 UTC, johnthagen commented
@kornelski Thank you for bringing this up and providing stats. This has been resolved in

@8573 Thank you for providing your perspective.

- #72